title: Vercel ✕ Octauthent demo
description: >-
  An Octauthent demo hosted on Vercel
baseurl: ""
url: "https://vercel.octauthent.com"
github_username:  octauthent

theme: minima
plugins:
  - jekyll-feed
