title: Vercel ✕ Octauthent demo
email: your-email@example.com
description: >-
  An Octauthent demo hosted on Vercel
baseurl: ""
url: "https://vercel.octauthent.com"
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed
